### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by IgorGanapolsky** [bbqsrc/android-autotools#2]
Hello,
I am unable to install your package.  I get this error:

> Collecting android-autotools
>   Downloading android-autotools-0.2.0.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/tmp/pip-build-Q7j5Pi/android-autotools/setup.py", line 2, in <module>
>         import android_autotools
>       File "android_autotools/**init**.py", line 60
>         def build(self, *args, inject=None):
>                                     ^
>     SyntaxError: invalid syntax

```
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-Q7j5Pi/android-  autotools/
```

**Comment by bbqsrc** [comment]
The code only works with Python 3.x. Are you trying with 2.x?
