### ISSUE TITLE
abuild.json not found

### ISSUE THREAD

**Issue by Jaykob** [bbqsrc/android-autotools#4]
I'm getting the following error, even when I don't specify a json build file using the -f argument. Or am I missing something here? 
```
$ abuild
usage: abuild [-h] [--version] [-v] [-a arch] [-o dir] [-R] [-f CONFIG]
abuild: error: argument -f: can't open 'abuild.json': [Errno 2] No such file or directory: 'abuild.json'
```

**Comment by bbqsrc** [comment]
By default, no parameters are required. It will try to open `abuild.json` unless `-f` points to another file. Much like `make` will find a Makefile.

**Comment by Jaykob** [comment]
OK, I wasn't under the impression that I need to provide a build.json file, as this is not explained anywhere. Is there a documentation that I'm missing? Sorry for the beginner questions ;)

**Comment by bbqsrc** [comment]
You can see https://github.com/bbqsrc/android-autotools/blob/master/demo.json for an example.
